spring:
  mail:
    password: # password
    username: noreply@tmdwo07278.cafe24.com
    host: smtp.cafe24.com
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          starttls:
            enable: false
    protocol: smtp
    port: 587
