spring:
  mail:
    password:
    username: victoryjay727@gmail.com
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          starttls:
            enable: true
    protocol: smtp
    port: 587
